version: '3'
services:
  php7:
    image: php:7.3-apache
    container_name: ts_php
    ports:
        - "80:80"
    volumes:
        - .:/var/www/html
    networks:
     - typescript
     
  node:
    image: node:8.16.0-alpine
    container_name: ts_node
    volumes:
        - .:/var/www/html
    tty: true
    ports:
        - "3000:3000"
    networks:
      - typescript

networks:
  typescript:
    driver: "bridge"
